[doc] add the empty parameter for text in readme.md (#157)
Following the https://github.com/com-lihaoyi/requests-scala/pull/66 ,
the PR is to add the empty parameter list to calls to geny's text()
method.

Because when I try to run with scala-3.4.1 with `r.text` , it fails with
```
[info] compiling 1 Scala source to /tmp/s/target/scala-3.4.1/classes ...
[error] -- [E100] Syntax Error: /tmp/s/src/main/scala/Main.scala:7:5 -------------------
[error] 7 |  r2.text
[error]   |  ^^^^^^^
[error]   |  method text in trait ByteData must be called with () argument
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed May 16, 2024, 12:35:38 PM
```